language: ruby
rvm:
  - 2.3.1
  - 2.4.0-preview3
services:
  - mysql
cache: bundler
before_script:
  - mv config/database.yml config/database.yml.old
  - cp config/database.yml.ci config/database.yml
  - RAILS_ENV=test bin/rails db:create db:schema:load
script:
  - bin/rails test
  - bundle exec codeclimate-test-reporter
install: bundle install
