language: ruby
rvm:
  - 2.3.0
services:
  - redis-server
cache:
  directories:
    - vendor/bundle
    - node_modules
script:
  - bin/rake db:migrate RAILS_ENV=test
  - CODECLIMATE_REPO_TOKEN=1898c1592d89355927dfccc9815ec3f91fa5fa32e2eb1333977b008d4c9e96dc bundle exec rake
install: bundle install
